fix(workflow): improve error handling in Nix flake check and build steps

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -35,11 +35,22 @@ jobs:
           name: maiko-nixos-build
           authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
 
-      - name: Test Nix Flake
+      - name: Check Nix Flake
         run: |
-          nix flake check --impure
+          output=$(nix flake check 2>&1)
+          status=$?
+
+          if [ $status -ne 0 ]; then
+            echo "::error:: title=Nix flake check failed::$(printf '%s' "$output")"
+          fi
+          exit $status
 
       - name: Build NixOS configuration
         run: |
-          nix build --impure .#nixosConfigurations.company.config.system.build.toplevel || true
-          nix build --impure .#nixosConfigurations.nixos-vm.config.formats.vm || true
+          output=$(nix build .#nixosConfigurations.company.config.system.build.toplevel 2>&1)
+          status=$?
+
+          if [ $status -ne 0 ]; then
+            echo "::error:: title=NixOS build failed::$(printf '%s' "$output")"
+          fi
+          exit $status
